"""Shared synthetic fixtures.

Nothing here touches the network, a GPU, or the Provo files, so the whole suite
runs on a laptop in under a minute.  The synthetic corpora are built so that the
truth is known: the generating delta, the generating window, and the tilt that
was injected are all available to the assertions.
"""

from __future__ import annotations

import numpy as np
import pytest

from lcsa.corpusdata import Corpus
from lcsa.kernels import POWER, marginalise
from lcsa.likelihood import NAIVE, evaluate_target


def make_corpus(n_targets=60, n_clusters=10, K_range=(3, 14), V_range=(6, 12),
                M=4, seed=0, drift=0.05):
    """A corpus whose ablation rows drift smoothly with depth, as real ones do."""
    rng = np.random.default_rng(seed)
    P_list, n_list, u_list, f_list, g_list, cl = [], [], [], [], [], []
    for t in range(n_targets):
        K = int(rng.integers(*K_range))
        V = int(rng.integers(*V_range))
        rows = [rng.dirichlet(np.ones(V) * 0.6)]
        for _ in range(K):
            nxt = np.abs(rows[-1] + rng.normal(scale=drift, size=V))
            rows.append(nxt / nxt.sum())
        P = np.asarray(rows)
        P /= P.sum(axis=1, keepdims=True)
        P_list.append(P)
        n_list.append(np.zeros(V))
        u_list.append(rng.dirichlet(np.ones(V)))
        f_list.append(rng.normal(size=(V, M)))
        g_list.append((rng.random(V) < 0.25).astype(float))
        cl.append(t % n_clusters)
    return Corpus(P_list, n_list, u_list, f_list, g_list, cl,
                  target_slots=[0] * n_targets)


def draw(corpus, theta, model=NAIVE, n_per_target=40, seed=1):
    """Draw multinomial responses from the model at ``theta``."""
    rng = np.random.default_rng(seed)
    counts = []
    for t in corpus:
        q = evaluate_target(t, np.asarray(theta, float), model, corpus.M).q
        counts.append(rng.multinomial(n_per_target, q).astype(float))
    return corpus.with_counts(counts)


def draw_true_delta(corpus, delta, nuisance=(0.1, 0.9), seed=1, n_per_target=40):
    """Responses generated by graded truncation at ``delta`` with a naive tilt."""
    theta = np.array([float(delta), float(nuisance[0]), float(nuisance[1])])
    return draw(corpus, theta, NAIVE, n_per_target=n_per_target, seed=seed)


@pytest.fixture
def rng():
    return np.random.default_rng(12345)


@pytest.fixture
def corpus():
    return make_corpus()


@pytest.fixture
def fitted_corpus():
    """Counts generated at delta = 0.316, i.e. a half-distance of 8 words."""
    return draw_true_delta(make_corpus(n_targets=80, n_clusters=10, seed=3), 0.316,
                           seed=7)


@pytest.fixture
def null_corpus():
    """Counts generated at delta = 0 exactly: full retention, no decay."""
    return draw_true_delta(make_corpus(n_targets=80, n_clusters=10, seed=4), 0.0,
                           seed=11)


def brute_marginal(P, delta, kernel=POWER):
    """Definition-level mixture, written out with a Python loop on purpose."""
    K = P.shape[0] - 1
    out = np.zeros(P.shape[1])
    for j in range(K + 1):
        r_j = 1.0 if j == 0 else float(kernel(np.array([j]), delta)[0])
        r_j1 = 0.0 if j == K else float(kernel(np.array([j + 1]), delta)[0])
        out += (r_j - r_j1) * P[j]
    return out


__all__ = ["make_corpus", "draw", "draw_true_delta", "brute_marginal", "marginalise"]
