"""The ten readers, all fitted through byte-identical code.

Every reader differs only in the source of the per-context response count
vector, and every synthetic reader receives exactly the response count its
context has in the human data.  That is the whole design: if the estimator
behaves differently across readers, the difference cannot come from sample size,
candidate sets, context lengths or the cache, because those are shared objects.

Floors
    ``N0`` draws responses independently from the fitted family with reader and
    reference the same checkpoint and true decay exactly zero.  ``N0-PRIME`` adds
    passage-level and target-level tilts along the nuisance score directions,
    scaled so that its design effect matches the human one.  N0 cannot detect the
    inflation the cluster-robust repair exists to catch, which is why the
    over-dispersed floor is the control that matters.

Zero-decay substantive nulls
    ``q_0 ∝ p_ref exp(alpha h)`` with retention exactly one at every distance.
    ``N-TOPIC`` and ``N-ORDER`` have ``h`` numerically orthogonalised within
    context against the measured span, so no nuisance parameter can express
    them.  ``N-LEX`` is lexical only and is deliberately left inside the repaired
    span; it is the null the criterion predicts the repaired estimator absorbs
    and the naive one does not, which is the prediction that can embarrass the
    theory.

Recovery ladder
    Eight readers generated by *actual* graded random truncation at known
    ``d_half``, one uniform draw per response, not by sampling the marginal.  The
    two coincide in distribution, and drawing the mask explicitly is what makes
    the ladder a test of the marginalisation rather than an assumption of it.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass

import numpy as np

from lcsa.corpusdata import PROB_FLOOR, Corpus
from lcsa.kernels import POWER, delta_from_d_half, truncation_weights
from lcsa.likelihood import Model, evaluate_target
from lcsa.projection import decompose, orthonormal_span
from lcsa.reliability import js_statistic

log = logging.getLogger(__name__)

__all__ = [
    "LADDER_DHALF",
    "ladder_deltas",
    "draw_counts",
    "reader_n0",
    "reader_n0_prime",
    "calibrate_n0_prime",
    "null_distributions",
    "tilt_directions",
    "tilted_cache",
    "calibrate_alpha",
    "reader_ladder",
    "human_js",
]

#: The eleven rungs, ``inf`` meaning no decay at all.  The three added inside
#: the registered window, 12, 20 and 24, are what let the identification
#: ceiling be read as a rate rather than as the single largest bounded rung.
LADDER_DHALF = (2.0, 4.0, 8.0, 12.0, 16.0, 20.0, 24.0, 32.0, 64.0, 128.0, float("inf"))


def ladder_deltas() -> list[float]:
    """``delta = ln 2 / ln(1 + d_half)`` at each rung."""
    return [delta_from_d_half(d) for d in LADDER_DHALF]


def draw_counts(
    corpus: Corpus, q_list: list[np.ndarray], rng: np.random.Generator
) -> list[np.ndarray]:
    """Multinomial draws at each target's own human response count."""
    out = []
    for t, tgt in enumerate(corpus):
        N = int(round(tgt.N))
        q = np.clip(np.asarray(q_list[t], dtype=np.float64), 0.0, None)
        s = q.sum()
        if N <= 0 or s <= 0:
            out.append(np.zeros(tgt.V, dtype=np.float64))
            continue
        out.append(rng.multinomial(N, q / s).astype(np.float64))
    return out


def _fitted_q(corpus: Corpus, theta: np.ndarray, model: Model, kernel=POWER) -> list[np.ndarray]:
    return [evaluate_target(t, theta, model, corpus.M, kernel).q for t in corpus]


def reader_n0(
    corpus: Corpus, theta0: np.ndarray, model: Model, seed: int = 0, kernel=POWER
) -> Corpus:
    """Self-reference floor: draws from the fitted family at ``delta = 0``."""
    if float(theta0[0]) != 0.0:
        raise ValueError(
            f"the floor must be generated at delta=0, got delta={theta0[0]}"
        )
    rng = np.random.default_rng(seed)
    return corpus.with_counts(draw_counts(corpus, _fitted_q(corpus, theta0, model, kernel), rng))


def reader_n0_prime(
    corpus: Corpus,
    theta0: np.ndarray,
    model: Model,
    sigma_passage: float,
    sigma_target: float = 0.0,
    seed: int = 0,
    kernel=POWER,
) -> Corpus:
    """Over-dispersed floor: random tilts along the nuisance directions.

    A tilt is drawn per passage and shared by every target in it, which is what
    makes responses within a passage dependent, plus a smaller independent tilt
    per target standing in for participant-level variation that aggregated
    counts cannot separate.  Both live in the nuisance span, so true decay stays
    exactly zero and the only thing that changes is the between-cluster variance
    of the score.
    """
    if float(theta0[0]) != 0.0:
        raise ValueError(f"the floor must be generated at delta=0, got delta={theta0[0]}")
    rng = np.random.default_rng(seed)
    M = corpus.M
    dim = model.dim(M) - 1
    xi = rng.normal(size=(corpus.n_clusters, dim))
    q_list = []
    for t, tgt in enumerate(corpus):
        fit = evaluate_target(tgt, theta0, model, M, kernel)
        B = orthonormal_span(fit.scores[:, 1:], fit.q)  # whitened, (V, k)
        k = B.shape[1]
        if k == 0:
            q_list.append(fit.q)
            continue
        coef = sigma_passage * xi[tgt.cluster, :k]
        if sigma_target > 0:
            coef = coef + sigma_target * rng.normal(size=k)
        # Back out of whitened coordinates; q floors keep this finite.
        s = np.sqrt(np.clip(fit.q, PROB_FLOOR, None))
        tilt = (B[:, :k] @ coef) / s
        tilt = np.clip(tilt - tilt.mean(), -20.0, 20.0)
        z = np.log(np.clip(fit.q, PROB_FLOOR, None)) + tilt
        z -= z.max()
        q = np.exp(z)
        q_list.append(q / q.sum())
    return corpus.with_counts(draw_counts(corpus, q_list, rng))


def calibrate_n0_prime(
    corpus: Corpus,
    theta0: np.ndarray,
    model: Model,
    target_design_effect: float,
    seed: int = 0,
    kernel=POWER,
    n_rep: int = 4,
    lo: float = 0.0,
    hi: float = 2.0,
    n_iter: int = 12,
    tol: float = 0.05,
) -> dict:
    """Bisection on the tilt scale so the floor reproduces a target design effect.

    The design effect is averaged over a few draws, since a single draw with 55
    clusters is noisy; the returned record carries the achieved value so that a
    calibration that failed to reach the target is visible rather than implied.
    """
    from lcsa.inference import score_test

    def deff(sig: float) -> float:
        vals = []
        for r in range(n_rep):
            c = reader_n0_prime(corpus, theta0, model, sig, seed=seed + 1000 * r + 1,
                                kernel=kernel)
            st = score_test(c, model, kernel, n_starts=1)
            if np.isfinite(st.design_effect):
                vals.append(st.design_effect)
        return float(np.mean(vals)) if vals else float("nan")

    base = deff(lo)
    top = deff(hi)
    if not np.isfinite(top) or top < target_design_effect:
        log.warning(
            "tilt scale %.2f reaches design effect %.2f, below the target %.2f; "
            "reporting the boundary", hi, top, target_design_effect
        )
        return {"sigma": hi, "design_effect": top, "target": target_design_effect,
                "baseline": base, "at_bound": True}
    a, b = lo, hi
    best = hi
    for i in range(n_iter):
        mid = 0.5 * (a + b)
        v = deff(mid)
        best = mid
        if not np.isfinite(v):
            b = mid
            continue
        if abs(v - target_design_effect) <= tol * max(target_design_effect, 1.0):
            return {"sigma": mid, "design_effect": v, "target": target_design_effect,
                    "baseline": base, "at_bound": False}
        if v < target_design_effect:
            a = mid
        else:
            b = mid
    return {"sigma": best, "design_effect": deff(best), "target": target_design_effect,
            "baseline": base, "at_bound": False}


def tilt_directions(
    corpus: Corpus,
    h_list: list[np.ndarray],
    theta0: np.ndarray | None = None,
    model: Model | None = None,
    orthogonalise: bool = True,
    kernel=POWER,
) -> list[np.ndarray]:
    """The unit-scale tilt direction per target, orthogonalised against the span.

    This is the only expensive part of a substantive null and it does not depend
    on ``alpha``, so it is computed once, saved by ``lcsa e3 --stage prepare``
    and reused by the E4 sweep to tilt every row of the same cache.
    """
    if orthogonalise and (theta0 is None or model is None):
        raise ValueError("orthogonalising against the span needs theta0 and a model")
    out = []
    for t, tgt in enumerate(corpus):
        h = np.asarray(h_list[t], dtype=np.float64)
        if h.shape != (tgt.V,):
            raise ValueError(
                f"target {t}: h has shape {h.shape}, expected {(tgt.V,)}"
            )
        if orthogonalise:
            fit = evaluate_target(tgt, theta0, model, corpus.M, kernel)
            _, perp = decompose(h, fit.scores[:, 1:], fit.q)
            s = np.sqrt(np.clip(fit.q, PROB_FLOOR, None))
            h = np.where(fit.q > 1e-10, perp / s, 0.0)
        h = h - h.mean()
        sd = h.std()
        if sd > 0:
            h = h / sd  # unit scale, so alpha means the same thing everywhere
        out.append(h)
    return out


def _tilt_row(row: np.ndarray, h: np.ndarray, alpha: float) -> np.ndarray:
    z = np.log(np.clip(row, PROB_FLOOR, None)) + alpha * h
    z -= z.max()
    q = np.exp(z)
    return q / q.sum()


def null_distributions(
    corpus: Corpus,
    h_list: list[np.ndarray],
    alpha: float,
    theta0: np.ndarray | None = None,
    model: Model | None = None,
    orthogonalise: bool = True,
    kernel=POWER,
    directions: list[np.ndarray] | None = None,
) -> list[np.ndarray]:
    """``q_0 ∝ p_ref^{(K)} exp(alpha h)`` with retention exactly one everywhere.

    ``p_ref^{(K)}`` is the full-context row of the cache, which is what the
    truncation mixture returns at ``delta = 0``, so the generated reader has no
    context decay by construction rather than by approximation.  ``directions``
    short-circuits the orthogonalisation when :func:`tilt_directions` has
    already been run.
    """
    if directions is None:
        directions = tilt_directions(corpus, h_list, theta0, model, orthogonalise, kernel)
    return [_tilt_row(tgt.P[-1], directions[t], alpha) for t, tgt in enumerate(corpus)]


def tilted_cache(corpus: Corpus, directions: list[np.ndarray], alpha: float) -> list[np.ndarray]:
    """Every ablation row tilted by the same ``exp(alpha h)``: a zero-decay reference.

    Its full-context row is the null's ``q_0`` and its depth-``j`` row is the
    reference's own depth-``j`` row under the same tilt, so the E4 sweep can run
    on it exactly as on a cache built under another checkpoint, at no GPU cost.
    """
    out = []
    for t, tgt in enumerate(corpus):
        h = np.asarray(directions[t], dtype=np.float64)
        out.append(np.stack([_tilt_row(tgt.P[j], h, alpha) for j in range(tgt.K + 1)]))
    return out


def human_js(corpus: Corpus) -> float:
    """Mean plug-in JS between the human counts and the full-context reference."""
    return js_statistic([t.n for t in corpus], [t.P[-1] for t in corpus])


def calibrate_alpha(
    corpus: Corpus,
    h_list: list[np.ndarray],
    target_js: float,
    theta0: np.ndarray | None = None,
    model: Model | None = None,
    orthogonalise: bool = True,
    seed: int = 0,
    kernel=POWER,
    lo: float = 0.0,
    hi: float = 8.0,
    n_iter: int = 20,
    rel_tol: float = 0.05,
) -> dict:
    """Tune ``alpha`` so the null's JS from the reference matches the human value.

    The match is like-for-like: the null's JS is computed from *simulated counts*
    at the human ``N_t`` through the same statistic applied to the human counts,
    so the small-sample bias of the divergence is common to both sides.  The 5
    percent tolerance is the one registered in the design.
    """
    rng_seed = seed
    dirs = tilt_directions(corpus, h_list, theta0, model, orthogonalise, kernel)

    def stat(a: float) -> float:
        q = null_distributions(corpus, h_list, a, directions=dirs)
        counts = draw_counts(corpus, q, np.random.default_rng(rng_seed))
        return js_statistic(counts, [t.P[-1] for t in corpus])

    v_lo, v_hi = stat(lo), stat(hi)
    if v_hi < target_js:
        log.warning(
            "alpha=%.2f only reaches JS %.4f against a target of %.4f; "
            "reporting the boundary", hi, v_hi, target_js
        )
        return {"alpha": hi, "js": v_hi, "target": target_js, "at_bound": True,
                "js_at_zero": v_lo}
    a, b = lo, hi
    best, best_v = hi, v_hi
    for i in range(n_iter):
        mid = 0.5 * (a + b)
        v = stat(mid)
        best, best_v = mid, v
        if abs(v - target_js) <= rel_tol * target_js:
            return {"alpha": mid, "js": v, "target": target_js, "at_bound": False,
                    "js_at_zero": v_lo}
        if v < target_js:
            a = mid
        else:
            b = mid
    return {"alpha": best, "js": best_v, "target": target_js, "at_bound": False,
            "js_at_zero": v_lo}


def reader_ladder(
    gen_corpus: Corpus,
    d_half: float,
    theta_nuisance: np.ndarray,
    model: Model,
    seed: int = 0,
    kernel=POWER,
    tilt: tuple[list[np.ndarray], float] | None = None,
) -> list[np.ndarray]:
    """Counts generated by explicit graded random truncation at a known ``d_half``.

    One uniform variate per response selects a retained depth from the ``K + 1``
    mask atoms, and the response is then drawn from the estimator applied to that
    depth's reference row.  ``gen_corpus`` carries the *generating* model's cache,
    which in the paper is GPT-2-large while fitting happens under Qwen2.5-1.5B, so
    recovery is measured in the misspecified regime.

    ``tilt = (directions, alpha)`` multiplies every depth's row by
    ``exp(alpha * direction_t)`` before the draw, which crosses real decay with
    a mismatch of a registered null; the depth draws are seeded the same way
    with and without the tilt, so a paired comparison of the two arms shares
    its retention lottery.
    """
    rng = np.random.default_rng(seed)
    delta = delta_from_d_half(d_half)
    M = gen_corpus.M
    out = []
    for tgt in gen_corpus:
        N = int(round(tgt.N))
        if N <= 0:
            out.append(np.zeros(tgt.V, dtype=np.float64))
            continue
        w = truncation_weights(tgt.K, delta, kernel)
        depths = rng.choice(tgt.K + 1, size=N, p=w)
        counts = np.zeros(tgt.V, dtype=np.float64)
        lam, beta = float(theta_nuisance[1]), float(theta_nuisance[2])
        for j, m in zip(*np.unique(depths, return_counts=True)):
            ptil = (1 - lam) * np.clip(tgt.P[int(j)], PROB_FLOOR, None) + lam * tgt.u
            z = beta * np.log(np.clip(ptil, PROB_FLOOR, None))
            if model.lexical:
                z = z + tgt.f @ np.asarray(theta_nuisance[3 : 3 + M])
            if model.prior_mention:
                z = z + float(theta_nuisance[-1]) * tgt.g
            if tilt is not None:
                z = z + float(tilt[1]) * np.asarray(tilt[0][tgt.index], dtype=np.float64)
            z -= z.max()
            q = np.exp(z)
            counts += rng.multinomial(int(m), q / q.sum()).astype(np.float64)
        out.append(counts)
    return out
